import React, { useState } from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';

import { PromptType, ChatLog } from '@/types';
import { useAppStore } from '@/stores/AppStore';
import prompts from '@/consts/prompts.json';

export default function Home() {
  const { chatLogs, sendPrompt, resetGame } = useAppStore();
  const [prompt, setPrompt]: PromptType = useState('');

  const onSubmit = (event: React.SyntheticEvent) => {
    event.preventDefault();
    sendPrompt({ prompt });
    setPrompt('');
  };

  const sendCharacterPrompt = () => sendPrompt({ prompt: prompts.generate_character });
  const sendBeginGamePrompt = () => sendPrompt({ prompt: prompts.begin_game });

  const onChange = (value: React.ChangeEvent<HTMLTextAreaElement>) => setPrompt(value.target.value);

  return (
    <>
      <Head>
        <title>DND</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.chatLogContainer}>
          {chatLogs.map((log: ChatLog, index: number) => (<div key={index} className={styles.log}>{log.content}</div>))}
        </div>

        <div className={styles.actionsContainer}>
          <form className={styles.form} onSubmit={onSubmit}>
            <textarea className={styles.promptText} value={prompt} name='text' onChange={onChange}></textarea>
            <button className={styles.button} type='submit'>Send</button>
          </form>

          <hr className={styles.break}></hr>

          <button className={styles.button} type='button' onClick={sendCharacterPrompt}>Get character</button>
          <button className={styles.button} type='button' onClick={sendBeginGamePrompt}>Begin game</button>

          <hr className={styles.break}></hr>

          <button className={styles.button} type='button' onClick={resetGame}>Reset game</button>
        </div>
      </main>
    </>
  )
}
