import { QA_PROMPT, SOFTWARE_ENGINEER_PROPMT, TWEETER_PROPMT } from '@/templates/prompts';

export const prompts = {
  ASSISTANT: QA_PROMPT,
  SOFTWARE_ENGINEER: SOFTWARE_ENGINEER_PROPMT,
  TWEETER: TWEETER_PROPMT,
};
